// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class headingupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(headingupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202501062136090_heading-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
